# Generated by Django 4.2.2 on 2023-06-25 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.PositiveBigIntegerField()),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('proposed_commencement_Date', models.DateField()),
                ('attachment_position_description', models.FileField(upload_to='vacancy_attachment')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.PositiveBigIntegerField()),
                ('additional_info', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('phone_number', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('work_experience', models.PositiveIntegerField()),
                ('current_police_check', models.BooleanField(default=False)),
                ('children_check', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=60)),
                ('cv', models.FileField(upload_to='cv_pdf')),
                ('qualification_pdf', models.FileField(upload_to='qualification_pdf')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('position_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.position')),
                ('qualification_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.qualification')),
            ],
        ),
    ]
