# Generated by Django 4.2.2 on 2023-07-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_service_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='homecare'),
        ),
        migrations.AlterField(
            model_name='service',
            name='main_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='sub_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
