# Generated by Django 4.2.2 on 2023-07-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_jobpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
