# Generated by Django 4.2.2 on 2023-07-31 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_vacancy_role_title_alter_vacancy_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='timesheet', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
        ),
    ]
